In [3]:
import numpy as np


In [4]:
# Empty array using empty function
# The function empty takes one parameters one that describes the dimension
empty_array = np.empty((2, 3))
print(empty_array)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.67022953e-307 2.11398144e-307 8.53042308e-312]]


In [5]:
# full array
# the function full() takes two parameters one is for the dimension the other for the  values 
full_array  = np.full((2, 3), 5)
print(full_array)

[[5 5 5]
 [5 5 5]]
